### ISSUE TITLE
Awesome! But the naming... 

### ISSUE THREAD

**Issue by silentwarrior** [0a-/butler#1]
This is awesome stuff, but the naming of stuff is not very intuitive wouldnt you say?

Awesome stuff none the less!

PS: maybe state in the docs that a quark is a template and a lepton a function to attach to a template

**Comment by 0a-** [comment]
Thanks! Yeah, I agree. Sacha Greif mentioned about that too. (http://crater.io/posts/E58wbKxmevmxtfELR) Right now I'm actually thinking of renaming the functions (e.g. "quark" into "bindTemplate") and the package. Do you have any suggestion on what I should rename the package?

**Comment by 0a-** [comment]
I just thought of a new name for the package & updated the naming scheme!

**Comment by silentwarrior** [comment]
Glad you changed, the new names are much more understandable.

**Comment by silentwarrior** [comment]
Let me try and build an example :

```
var renderedList = [];
var whenRendered = Butler.makeLogic(function(){
   renderedList.push(this.itemName);
   console.log(renderedList);
},function(){
   renderedList.splice(renderedList.indexOf(this.itemName),1);
   console.log(renderedList);
});

// change the background color to red on mouse over and back on mouse out
var debugableItem = Butler.makeLogic(function(){
   // using $(selector).hover(inFunction,outFunction)
   var oldColor;
   var inFunction = function(){ 
         oldColor = $(this).css("background-color"); 
         $(this).css("background-color","red"); 
    };
   var outFunction = function(){ $(this).css("background-color", oldColor); }
    $(this).hover(inFunction,outFunction);
});

Butler.bond("template1",[whenRendered, debugableItem],{itemName:"i am template 1"});
Butler.bond("template2",[whenRendered, debugableItem],{itemName:"i am template 2"});

```


Would this work? The dependency is also very useful, but I cant think of a simple example right now.

**Comment by 0a-** [comment]
Yup it would work except for the `this.itemName` part because you need to use `Butler.env.itemName` to access the variables.

**Comment by 0a-** [comment]
By the way inside `Butler.makeLogic(function(){...})`, `this` would always refer to `window`, just like inside `Template.rendered = function(){...}`

**Comment by 0a-** [comment]
`this` now refers to the Template that the logic function is bound to. #3
