### ISSUE TITLE
New Name still not on atmosphere

### ISSUE THREAD

**Issue by silentwarrior** [0a-/butler#2]
Hello

For example, in the following meteor pad : http://meteorpad.com/pad/mBgAGQR5dDS7CwsiR/Leaderboard

You can see that arch:fermions is there, but not the new arch:template-butler

**Comment by 0a-** [comment]
Hmm somehow it is not listed in meteorpad. It would be added to the app if one one does `meteor add arch:template-butler`. (it can be found on atmosphere here https://atmospherejs.com/arch/template-butler)

**Comment by 0a-** [comment]
I think it is either a problem with meteorpad (you can consider opening an issue here https://github.com/rissem/meteorpad) or atmosphere (or here https://github.com/Atmosphere/atmosphere/issues).

**Comment by 0a-** [comment]
Just checked. It is on meteor pad now. (Maybe the new push to atmosphere fixed the inconsistency?)
